### ISSUE TITLE
restful_model error when created_at is null

### ISSUE THREAD

**Issue by twojustin** [inboxapp/inbox-ruby#11]
when i mock the response for account as: 
```js
{
  id: "ACCOUNT_ID",
  namespace_id: "NAMESPACE_ID",
  created_at: null,
  account_id: "ACCOUNT_ID",
  trial: false,
  trial_expires: null,
  sync_state: "running",
  billing_state: "trial-expired"
}
```

it raises type error:
```
TypeError:
       can't convert nil into an exact number
```

**Comment by jennielees** [comment]
`created_at` isn't usually in the response - do you need it?

either way, just committed cf66a0eac6406cb711c3a18f74a99d79b2578045 which stops a force conversion from happening. :)

**Comment by twojustin** [comment]
i don't need created_at, it's being passed back by accounts api
