### ISSUE TITLE
Dropping Ruby 1.x support?

### ISSUE THREAD

**Issue by singjsong** [inboxapp/inbox-ruby#13]
Is this a possibility for you guys? Or are there customers that really depend on having this support? In addition to some additions I've been doing, I wanted to also do refactoring, some of which is modernizing the syntax. Wanted to ask before I did the work. Thanks!

**Comment by khamidou** [comment]
Hi Jake,

We're not planning to drop ruby 1.x support unless we have a very good reason to do it. However, I'm curious about what changes you'd like to introduce. Could you tell me more about it?

k

**Comment by singjsong** [comment]
Regarding 1.x support: fair enough. Was just curious.

The biggest additions to the gem that we'd need is integration with the delta sync API endpoint. Having this piece would allow us to go forward with fully integrating Nilas into our back end for our users. But we're also juggling about 20 other things at the moment. I've started building it in my free time but can't say that it would get done in a timely fashion.

**Comment by khamidou** [comment]
Yes. It's on our feature list but unfortunately I don't know when we'll implement it. However, I'd be glad to help you understand the sdk/review your code. You can email me at karim@nilas.com.
