### ISSUE TITLE
Message.file_ids no longer available

### ISSUE THREAD

**Issue by vmotsak** [inboxapp/inbox-ruby#14]
It looks like `file_ids` in Message always empty,probably cause it's not longer present in api response, yet response contains  files collection

        "files": [
            {
                "content_type": "image/png",
                "filename": "file.png",
                "id": "aaaaaaaaaaaaaaaaaaaaa",
                "size": 18745
            }
        ]

so file collection can be build without extra request to api 

    def files
      @files ||= RestfulModelCollection.new(File, @_api, @namespace_id, {:message_id=>@id})
    end

**Comment by khamidou** [comment]
Yeah `file_ids` is code rot. I've just removed it. You should use `#files` instead.

**Comment by vmotsak** [comment]
What about attaching files to drafts?

    def attach(file)
      file.save! unless file.id
      @file_ids.push(file.id)
    end

still in the code.
