### ISSUE TITLE
Allow support for Delta Sync

### ISSUE THREAD

**Issue by nikhils777** [inboxapp/inbox-ruby#3]
This gem does not currently provide support for the Delta Sync API provided by inbox.
The following api requests are available for the Delta Sync API, Obtaining a Delta Sync Cursor, Requesting a Delta, Streaming Delta Updates, and Getting a Subset of all changes . https://www.inboxapp.com/docs/api#sync-protocol . How can these requests be made available via the ruby gem?

**Comment by spang** [comment]
Hi @nikhils777, we're working on some functional changes to how the Delta Sync API works right now, so we haven't added support for it to the SDKs. If you really need it now, feel free to fork the repo and add support yourself, however. :)
