### ISSUE TITLE
draft.send! has unexpected result

### ISSUE THREAD

**Issue by grinich** [inboxapp/inbox-ruby#4]
**Filed by Justin Zhang @ PersistIQ:**

i'm using Inbox::Draft.send! to send, and save the draft_id to follow up on the deliver status, 

however, the returned draft object from .send! method does not populate any fields from the api response. specifically, id, thread_id, are not populated.

https://github.com/inboxapp/inbox-ruby/blob/master/lib/draft.rb#L24

i've confirmed that the api does respond with id, thread_id, when i call .../n/ns_id/send

**Comment by khamidou** [comment]
Fixed by c782432f069c7b50ced0af089d687fa23bf0e87c.
