### ISSUE TITLE
getting raw text messages

### ISSUE THREAD

**Issue by annieogrady** [inboxapp/inbox-ruby#6]
we are trying to get the raw message of an email  (shown here in your documentation)
http://take.ms/ZEqWu

however, when we try, we are not seeing it.
http://take.ms/CHaJq

any suggestions?  are we doing something wrong?

**Comment by emfree** [comment]
Are you using the latest version of the gem (`0.13.0`)?

**Comment by annieogrady** [comment]
thanks - no - we were on a later one.

Annie O'Grady
Co-founder
AgentBright, Inc
3544 Crown Point Road
Louisville, TN 37777
860-575-6950

**Comment by annieogrady** [comment]
oops - earlier one.

Annie O'Grady
Co-founder
AgentBright, Inc
3544 Crown Point Road
Louisville, TN 37777
860-575-6950
