### ISSUE TITLE
Draft destroy

### ISSUE THREAD

**Issue by vmotsak** [inboxapp/inbox-ruby#7]
Trying to delete draft message like this

    dr = @inbox.namespaces.first.drafts.find('8u8topdztixj57ln8kk26gelk')
    dr.destroy

Returns an error

    ArgumentError: wrong number of arguments (3 for 1..2)
    from ....../gems/rest-client-1.7.2/lib/restclient.rb:80:in `delete'

Attempt to call RestClient directly results in BadRequest

    ::RestClient.delete dr.url

    RestClient::BadRequest: 400 Bad Request
    from ......./gems/rest-client-1.7.2/lib/restclient/abstract_response.rb:48:in `return!'

**Comment by singjsong** [comment]
Was just about to create an issue for this. Same thing as well, regardless of what resource.

**Comment by khamidou** [comment]
I'm looking into this.

**Comment by khamidou** [comment]
Fixed in 56efdf0.
