### ISSUE TITLE
Error: Sorry,  you must provide a valid 'client_id' for open source version

### ISSUE THREAD

**Issue by silab** [inboxapp/inbox-ruby#8]
Hi,

i am using your example with the opensource version of inbox, and it gives me this error.

```
{"reason"=>"Sorry,
 you must provide a valid `client_id`. The `client_id` request parameter should be the App ID of your application in the Inbox Developer Portal.",
 "error"=>"access_denied"}
```

i am connecting to the server with the following code.

```
def login
		inbox = Inbox::API.new(nil, nil, nil, 'http://localhost:5555/')
	  user_email = 'john@test.com'
	  callback_url = url_for(:action => 'login_callback')
	  redirect_to inbox.url_for_authentication(callback_url, user_email)
	end
```

the rails console is showing, that the app still tries to connect to inboxapp.com

```
Processing by MailsController#login as HTML
Redirected to https://www.inboxapp.com/oauth/authorize?client_id=&trial=false&response_type=code&scope=email&login_hint=john@test.com&redirect_uri=http://lvh.me:3000/mails/login_callback
```

why would it redirect to inboxapp.com? why isn't it using my local opensource version?

**Comment by khamidou** [comment]
Hi Silab,

The rails example uses our hosted API. Here's what your controller should be doing when using the opensource API:

```ruby
def logged_in
      inbox = Inbox::API.new(nil, nil, nil, 'http://localhost:5555/')
      # There's no need to authentify the user --- there's no access control in the opensource version.
      @first_message = inbox.namespaces.first.messages.first.snippet
end
```
If you want to add an user inbox, you'll have to do it from the command line. Login to your vagrant box, and run `bin/inbox-auth john@test.com` from the `/vagrant` directory.

Karim

**Comment by silab** [comment]
Hi,

thx for the reply. so how can access the inboxes of different users? say i have authenticated many users, now i want to show every user his emails. how would i do this this the open source version? if you could provide me with a short code snippet would be awesome.

regards

--
Silab Kamawall
silab.kamawall@gmail.com

**Comment by khamidou** [comment]
It's super easy with the namespaces collection:

```ruby
inbox.namespaces.each do | namespace |
    puts namespace['email_address']
end
```

See the README for more examples.
